context.initializer.classes: com.ing.trading.fx.processingunit.PUApplicationBeansInitializer

hazelcast:
  monitoring: true
  maxSize: 10000
  namespace: hazelcast
  tcp:
    enabled: true
    members: "localhost:5701"
