context.initializer.classes: com.ing.fx.trading.marketclient.MarketClientApplicationBeansInitializer

server:
  port: 8082

hazelcast:
  initialBackoffMillis: 1000
  maxBackoffMillis: 6000
  multiplier: 2.0
  clusterConnectTimeoutMillis: 50000
  jitter: 0.2
  asyncStartClient: true
  namespace: hazelcast
  userCodeDeploymentEnabled: true
  clientProperties:
    hazelcast.client.invocation.timeout.seconds: 5
  executorServiceName: trader-cli
  tcp:
    enabled: true
    members: localhost:5701

